name: healthReport

on:
#  push:
#    branches:
#      - master
  schedule:
    - cron: '0 4 * * *' # GMT+8 12:00, 19:00
  workflow_dispatch: # add manually button

jobs:
  start:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run Spider
        run: |
          python health_report_helper/main.py "${{ secrets.DATA }}"
